[CAMPFIRE]
CAMPFIRE_LIT_TIME = 1728000
CAMPFIRE_RUN_OUT_INDICATOR_TIME = 600
CAMPFIRE_RAIN_UNLIT_TIME = 160
CAMPFIRE_RAIN_PARTICLE_FACTOR = 2
CAMPFIRE_DROPS_ITEMS_WHEN_UNLIT_BY_TIME_OR_RAIN = true
CAMPFIRE_BREAKS_WHEN_UNLIT_BY_TIME = false
CAMPFIRE_ADDING_BURNABLES = true
CAMPFIRE_MAX_LIT_TIME = 2000
CAMPFIRE_AFFECTED_BY_SLEEP_TIME = false
GENERATED_CAMPFIRE_IS_LIT_INFINITELY = true
[SOUL_CAMPFIRE]
SOUL_CAMPFIRE_LIT_TIME = 1728000
SOUL_CAMPFIRE_RUN_OUT_INDICATOR_TIME = 600
SOUL_CAMPFIRE_RAIN_UNLIT_TIME = -1
SOUL_CAMPFIRE_RAIN_PARTICLE_FACTOR = 2
SOUL_CAMPFIRE_DROPS_ITEMS_WHEN_UNLIT_BY_TIME_OR_RAIN = true
SOUL_CAMPFIRE_BREAKS_WHEN_UNLIT_BY_TIME = false
SOUL_CAMPFIRE_ADDING_BURNABLES = true
SOUL_CAMPFIRE_MAX_LIT_TIME = 2000
SOUL_CAMPFIRE_AFFECTED_BY_SLEEP_TIME = false
GENERATED_SOUL_CAMPFIRE_IS_LIT_INFINITELY = true
